// ============================================================
// MBTI 93道标准测试题目
// 第一部分 1-26: E/I (外向/内向)
// 第二部分 27-52: S/N (感觉/直觉)
// 第三部分 53-78: T/F (思考/情感)
// 第四部分 79-93: J/P (判断/感知)
// ============================================================

const questions = [
  // ==================== 第一部分：E/I (1-26) ====================
  { id: 1, dimension: 'EI', text: '当你参加一个社交聚会时，你通常会：', options: { A: '与很多人交谈，包括陌生人', B: '只与少数几个熟悉的人交谈' }, mapping: { A: 'E', B: 'I' } },
  { id: 2, dimension: 'EI', text: '在闲暇时间，你更喜欢：', options: { A: '和朋友一起度过', B: '独自享受安静的时光' }, mapping: { A: 'E', B: 'I' } },
  { id: 3, dimension: 'EI', text: '当你需要充电恢复精力时，你会：', options: { A: '出去社交、与人互动', B: '独处、安静地思考' }, mapping: { A: 'E', B: 'I' } },
  { id: 4, dimension: 'EI', text: '在团体讨论中，你通常：', options: { A: '先发言，边想边说', B: '先倾听，想好再说' }, mapping: { A: 'E', B: 'I' } },
  { id: 5, dimension: 'EI', text: '你更倾向于：', options: { A: '拥有广泛的朋友圈', B: '拥有少数几个深交的朋友' }, mapping: { A: 'E', B: 'I' } },
  { id: 6, dimension: 'EI', text: '接到电话时，你的第一反应是：', options: { A: '快速接起来聊聊', B: '先看看是谁，犹豫一下再接' }, mapping: { A: 'E', B: 'I' } },
  { id: 7, dimension: 'EI', text: '当你在一个陌生城市时，你会：', options: { A: '主动找人问路或攀谈', B: '自己看地图慢慢找' }, mapping: { A: 'E', B: 'I' } },
  { id: 8, dimension: 'EI', text: '对于成为大家关注的焦点，你：', options: { A: '感到自在，甚至享受', B: '尽量回避，觉得不自在' }, mapping: { A: 'E', B: 'I' } },
  { id: 9, dimension: 'EI', text: '在团队项目中，你更喜欢：', options: { A: '和大家一起头脑风暴', B: '先独自思考再分享想法' }, mapping: { A: 'E', B: 'I' } },
  { id: 10, dimension: 'EI', text: '你更倾向于通过什么方式表达自己：', options: { A: '口头表达，边说边理清思路', B: '书面表达，仔细推敲后再呈现' }, mapping: { A: 'E', B: 'I' } },
  { id: 11, dimension: 'EI', text: '周末你更愿意：', options: { A: '安排满各种活动', B: '轻松随意，没有太多安排' }, mapping: { A: 'E', B: 'I' } },
  { id: 12, dimension: 'EI', text: '你更倾向于：', options: { A: '行动之后再思考', B: '思考之后再行动' }, mapping: { A: 'E', B: 'I' } },
  { id: 13, dimension: 'EI', text: '在会议上，你通常是：', options: { A: '积极发言的那一个', B: '安静聆听的那一个' }, mapping: { A: 'E', B: 'I' } },
  { id: 14, dimension: 'EI', text: '当你感到沮丧时，你会：', options: { A: '找朋友倾诉', B: '自己消化情绪' }, mapping: { A: 'E', B: 'I' } },
  { id: 15, dimension: 'EI', text: '你更擅长：', options: { A: '主动发起对话', B: '回应他人的话题' }, mapping: { A: 'E', B: 'I' } },
  { id: 16, dimension: 'EI', text: '在学习和工作中，你：', options: { A: '喜欢与人讨论和交流', B: '喜欢独自研究和思考' }, mapping: { A: 'E', B: 'I' } },
  { id: 17, dimension: 'EI', text: '社交活动结束后，你通常会感到：', options: { A: '精力充沛', B: '筋疲力尽，需要独处充电' }, mapping: { A: 'E', B: 'I' } },
  { id: 18, dimension: 'EI', text: '你更倾向于通过什么方式认识世界：', options: { A: '走出去亲身体验', B: '阅读和思考来理解' }, mapping: { A: 'E', B: 'I' } },
  { id: 19, dimension: 'EI', text: '在餐馆里发现菜里有问题，你会：', options: { A: '立刻叫服务员过来说明', B: '犹豫要不要说，或者就算了' }, mapping: { A: 'E', B: 'I' } },
  { id: 20, dimension: 'EI', text: '你更认同：', options: { A: '独乐乐不如众乐乐', B: '宁静致远，独处亦有乐趣' }, mapping: { A: 'E', B: 'I' } },
  { id: 21, dimension: 'EI', text: '你的说话风格更偏向：', options: { A: '语速较快，想到什么说什么', B: '语速较慢，字斟句酌' }, mapping: { A: 'E', B: 'I' } },
  { id: 22, dimension: 'EI', text: '面对新环境，你通常会：', options: { A: '快速融入，主动认识人', B: '先观察，慢慢适应' }, mapping: { A: 'E', B: 'I' } },
  { id: 23, dimension: 'EI', text: '在工作中遇到难题，你倾向于：', options: { A: '马上找同事讨论解决', B: '自己先研究，实在不行再求助' }, mapping: { A: 'E', B: 'I' } },
  { id: 24, dimension: 'EI', text: '你更喜欢的工作环境是：', options: { A: '开放式办公室，周围有人', B: '安静的独立空间' }, mapping: { A: 'E', B: 'I' } },
  { id: 25, dimension: 'EI', text: '你对认识新朋友的态度是：', options: { A: '觉得新鲜有趣，乐于结交', B: '比较谨慎，需要时间了解' }, mapping: { A: 'E', B: 'I' } },
  { id: 26, dimension: 'EI', text: '你的内心世界更偏向：', options: { A: '向外投射，关注外部世界', B: '向内探索，关注内心世界' }, mapping: { A: 'E', B: 'I' } },

  // ==================== 第二部分：S/N (27-52) ====================
  { id: 27, dimension: 'SN', text: '你更倾向于相信：', options: { A: '亲身经历和实际观察到的', B: '直觉和第六感' }, mapping: { A: 'S', B: 'N' } },
  { id: 28, dimension: 'SN', text: '阅读一本书时，你更关注：', options: { A: '具体的情节和细节描写', B: '背后的主题和隐含意义' }, mapping: { A: 'S', B: 'N' } },
  { id: 29, dimension: 'SN', text: '学习新知识时，你更喜欢：', options: { A: '循序渐进的实操练习', B: '先了解整体框架和理论' }, mapping: { A: 'S', B: 'N' } },
  { id: 30, dimension: 'SN', text: '你更擅长处理：', options: { A: '具体、实际的问题', B: '抽象、概念性的问题' }, mapping: { A: 'S', B: 'N' } },
  { id: 31, dimension: 'SN', text: '描述一个事物时，你更侧重：', options: { A: '客观事实和具体细节', B: '整体印象和联想比喻' }, mapping: { A: 'S', B: 'N' } },
  { id: 32, dimension: 'SN', text: '面对一项任务，你通常：', options: { A: '按照已有的方法，一步一步完成', B: '尝试新的方式，看看有没有更好的办法' }, mapping: { A: 'S', B: 'N' } },
  { id: 33, dimension: 'SN', text: '在做决定时，你更依赖：', options: { A: '过往的经验和数据', B: '对未来的预感和想象' }, mapping: { A: 'S', B: 'N' } },
  { id: 34, dimension: 'SN', text: '你更欣赏哪种类型的人：', options: { A: '脚踏实地的实干家', B: '天马行空的梦想家' }, mapping: { A: 'S', B: 'N' } },
  { id: 35, dimension: 'SN', text: '在旅行中，你更倾向于：', options: { A: '按攻略打卡，享受具体的体验', B: '随性漫游，感受旅途的氛围' }, mapping: { A: 'S', B: 'N' } },
  { id: 36, dimension: 'SN', text: '你更经常思考的是：', options: { A: '当下正在发生的事', B: '未来的各种可能性' }, mapping: { A: 'S', B: 'N' } },
  { id: 37, dimension: 'SN', text: '组装一个新家具时，你会：', options: { A: '严格按照说明书一步步来', B: '先大致看看，凭感觉组装' }, mapping: { A: 'S', B: 'N' } },
  { id: 38, dimension: 'SN', text: '在解决问题时，你更偏向：', options: { A: '试试看哪些方案实际有效', B: '从理论上分析各种可能方案' }, mapping: { A: 'S', B: 'N' } },
  { id: 39, dimension: 'SN', text: '你更容易记住：', options: { A: '人的面孔和具体事件', B: '人的气场和给你的感觉' }, mapping: { A: 'S', B: 'N' } },
  { id: 40, dimension: 'SN', text: '面对一个复杂的概念，你：', options: { A: '需要一个具体的例子来理解', B: '直接理解抽象概念也不困难' }, mapping: { A: 'S', B: 'N' } },
  { id: 41, dimension: 'SN', text: '你更喜欢的工作任务是：', options: { A: '有明确步骤和可衡量的结果', B: '需要创意和想象力的开放式任务' }, mapping: { A: 'S', B: 'N' } },
  { id: 42, dimension: 'SN', text: '你对细节的看法是：', options: { A: '细节决定成败，很重视', B: '把握大方向，细节可以灵活处理' }, mapping: { A: 'S', B: 'N' } },
  { id: 43, dimension: 'SN', text: '在听别人说话时，你更容易注意：', options: { A: '对方具体说了什么', B: '对方的言外之意和情绪' }, mapping: { A: 'S', B: 'N' } },
  { id: 44, dimension: 'SN', text: '你对创新的态度是：', options: { A: '尊重传统和经过验证的方法', B: '喜欢尝试新鲜和不同的方法' }, mapping: { A: 'S', B: 'N' } },
  { id: 45, dimension: 'SN', text: '在观察一幅画时，你先注意到的是：', options: { A: '画面的色彩、构图等具体元素', B: '画面传达的情感和意境' }, mapping: { A: 'S', B: 'N' } },
  { id: 46, dimension: 'SN', text: '当你看到一座山时，你首先想到：', options: { A: '这座山有多高、在什么地方', B: '山间的风景和自然之美' }, mapping: { A: 'S', B: 'N' } },
  { id: 47, dimension: 'SN', text: '你更倾向于通过什么方式了解一个新产品：', options: { A: '看参数、评测和实际表现', B: '看设计理念和品牌故事' }, mapping: { A: 'S', B: 'N' } },
  { id: 48, dimension: 'SN', text: '你的思维方式更偏向：', options: { A: '线性、有逻辑的', B: '跳跃、发散的' }, mapping: { A: 'S', B: 'N' } },
  { id: 49, dimension: 'SN', text: '在回忆过去时，你更清晰的是：', options: { A: '具体的事件经过和细节', B: '当时的感受和整体印象' }, mapping: { A: 'S', B: 'N' } },
  { id: 50, dimension: 'SN', text: '你喜欢的工作节奏是：', options: { A: '专注做好当前一件事', B: '多件事同时推进，保持变化' }, mapping: { A: 'S', B: 'N' } },
  { id: 51, dimension: 'SN', text: '在团队讨论中，你更容易被哪种观点打动：', options: { A: '数据详实、逻辑严密的观点', B: '视野开阔、富有远见的观点' }, mapping: { A: 'S', B: 'N' } },
  { id: 52, dimension: 'SN', text: '你对规则和流程的态度是：', options: { A: '尊重规则，照章办事更高效', B: '规则是死的，必要时可以变通' }, mapping: { A: 'S', B: 'N' } },

  // ==================== 第三部分：T/F (53-78) ====================
  { id: 53, dimension: 'TF', text: '在做重要决定时，你更依赖：', options: { A: '逻辑分析和客观事实', B: '内心的感受和价值观' }, mapping: { A: 'T', B: 'F' } },
  { id: 54, dimension: 'TF', text: '当朋友向你倾诉烦恼时，你首先会：', options: { A: '帮他分析问题，给出解决方案', B: '先共情、安慰，让他感到被理解' }, mapping: { A: 'T', B: 'F' } },
  { id: 55, dimension: 'TF', text: '在处理冲突时，你更看重：', options: { A: '谁对谁错，找到合理的解决方式', B: '维护和谐的人际关系' }, mapping: { A: 'T', B: 'F' } },
  { id: 56, dimension: 'TF', text: '你更认同以下哪种观点：', options: { A: '真理比人情更重要', B: '人情比真理更重要' }, mapping: { A: 'T', B: 'F' } },
  { id: 57, dimension: 'TF', text: '在工作中，你更倾向于：', options: { A: '以效率和结果为导向', B: '以人和团队氛围为导向' }, mapping: { A: 'T', B: 'F' } },
  { id: 58, dimension: 'TF', text: '别人评价你时，通常会说你：', options: { A: '理性、客观、善于分析', B: '温柔、善解人意、富有同理心' }, mapping: { A: 'T', B: 'F' } },
  { id: 59, dimension: 'TF', text: '当你需要批评别人时，你会：', options: { A: '直接指出问题，就事论事', B: '措辞委婉，尽量不伤害对方' }, mapping: { A: 'T', B: 'F' } },
  { id: 60, dimension: 'TF', text: '你更容易被以下哪种情况说服：', options: { A: '有逻辑、有数据支撑的论证', B: '触动人心、引发共鸣的故事' }, mapping: { A: 'T', B: 'F' } },
  { id: 61, dimension: 'TF', text: '在团队中，你最不能忍受：', options: { A: '效率低下、逻辑混乱', B: '冷漠无情、勾心斗角' }, mapping: { A: 'T', B: 'F' } },
  { id: 62, dimension: 'TF', text: '当你发现一个事实会伤害别人时，你会：', options: { A: '选择诚实，说出事实', B: '选择善意，适当保留' }, mapping: { A: 'T', B: 'F' } },
  { id: 63, dimension: 'TF', text: '在选择职业时，你更看重：', options: { A: '薪资、发展空间等客观条件', B: '是否感兴趣、是否符合自己的价值观' }, mapping: { A: 'T', B: 'F' } },
  { id: 64, dimension: 'TF', text: '你看待世界的方式更偏向：', options: { A: '客观公正、一视同仁', B: '因人而异、有情有义' }, mapping: { A: 'T', B: 'F' } },
  { id: 65, dimension: 'TF', text: '在做一个决定时，你通常：', options: { A: '先列出利弊分析表', B: '先感受内心的倾向' }, mapping: { A: 'T', B: 'F' } },
  { id: 66, dimension: 'TF', text: '听到别人的不幸遭遇时，你：', options: { A: '思考如何从制度上避免类似问题', B: '感同身受，心里很难过' }, mapping: { A: 'T', B: 'F' } },
  { id: 67, dimension: 'TF', text: '你更欣赏哪种领导风格：', options: { A: '公平严格、赏罚分明的', B: '关心下属、有人情味的' }, mapping: { A: 'T', B: 'F' } },
  { id: 68, dimension: 'TF', text: '在和别人争论时，你：', options: { A: '据理力争，直到问题水落石出', B: '尽量避免激烈争论，伤和气不值得' }, mapping: { A: 'T', B: 'F' } },
  { id: 69, dimension: 'TF', text: '判断一个行为对错时，你更依据：', options: { A: '普适的原则和标准', B: '具体情境和当事人的处境' }, mapping: { A: 'T', B: 'F' } },
  { id: 70, dimension: 'TF', text: '在做项目时，你更关注：', options: { A: '项目的目标和任务是否完成', B: '团队成员的感受和合作是否愉快' }, mapping: { A: 'T', B: 'F' } },
  { id: 71, dimension: 'TF', text: '你通常给人的印象是：', options: { A: '冷静理性，不容易被情绪左右', B: '热情温暖，容易感知他人情绪' }, mapping: { A: 'T', B: 'F' } },
  { id: 72, dimension: 'TF', text: '你更看重一个人：', options: { A: '能力和成就', B: '品格和善良' }, mapping: { A: 'T', B: 'F' } },
  { id: 73, dimension: 'TF', text: '接到一个复杂任务时，你首先会想：', options: { A: '什么是最有效率的完成方式', B: '这件事能带来什么样的价值和意义' }, mapping: { A: 'T', B: 'F' } },
  { id: 74, dimension: 'TF', text: '当别人质疑你的观点时，你：', options: { A: '乐于辩论，用论据为自己辩护', B: '觉得不舒服，可能选择回避' }, mapping: { A: 'T', B: 'F' } },
  { id: 75, dimension: 'TF', text: '你更倾向于：', options: { A: '客观公正，不被人情左右', B: '有温度有同理心，不冷漠无情' }, mapping: { A: 'T', B: 'F' } },
  { id: 76, dimension: 'TF', text: '评价一部电影时，你更看重：', options: { A: '剧情逻辑是否严丝合缝', B: '情感表达是否打动人心' }, mapping: { A: 'T', B: 'F' } },
  { id: 77, dimension: 'TF', text: '在帮助别人时，你更倾向于：', options: { A: '提供实用的建议和资源', B: '提供情感上的支持和陪伴' }, mapping: { A: 'T', B: 'F' } },
  { id: 78, dimension: 'TF', text: '你认为自己是一个：', options: { A: '先想清楚再做决定的人', B: '先感受清楚再做决定的人' }, mapping: { A: 'T', B: 'F' } },

  // ==================== 第四部分：J/P (79-93) ====================
  { id: 79, dimension: 'JP', text: '对于日程安排，你更喜欢：', options: { A: '提前做好详细计划', B: '随性而为，看当天心情' }, mapping: { A: 'J', B: 'P' } },
  { id: 80, dimension: 'JP', text: '当你要完成一项任务时，通常：', options: { A: '尽早开始，按计划推进', B: '等到截止日期前再集中冲刺' }, mapping: { A: 'J', B: 'P' } },
  { id: 81, dimension: 'JP', text: '你的桌面/房间通常是：', options: { A: '整洁有序，东西各有其位', B: '有些凌乱但你能找到东西' }, mapping: { A: 'J', B: 'P' } },
  { id: 82, dimension: 'JP', text: '面对突如其来的变化，你：', options: { A: '感到不安，希望恢复原计划', B: '觉得有趣，乐于灵活应对' }, mapping: { A: 'J', B: 'P' } },
  { id: 83, dimension: 'JP', text: '你更喜欢哪种工作方式：', options: { A: '有明确的截止日期和里程碑', B: '自由灵活，没有严格的时间限制' }, mapping: { A: 'J', B: 'P' } },
  { id: 84, dimension: 'JP', text: '在旅行前，你通常会：', options: { A: '做好详细的行程安排', B: '定好大方向，到了再随机应变' }, mapping: { A: 'J', B: 'P' } },
  { id: 85, dimension: 'JP', text: '做决定时，你倾向于：', options: { A: '尽快做出决定，然后执行', B: '保持开放，等待更多信息再做决定' }, mapping: { A: 'J', B: 'P' } },
  { id: 86, dimension: 'JP', text: '你更看重：', options: { A: '按时完成，遵守承诺', B: '随机应变，享受过程' }, mapping: { A: 'J', B: 'P' } },
  { id: 87, dimension: 'JP', text: '你的生活更偏向：', options: { A: '规律有序，有固定的习惯', B: '灵活多变，不喜欢被束缚' }, mapping: { A: 'J', B: 'P' } },
  { id: 88, dimension: 'JP', text: '当项目进展顺利时，你：', options: { A: '继续按计划执行，不喜欢节外生枝', B: '会想试试是否有更好的方法' }, mapping: { A: 'J', B: 'P' } },
  { id: 89, dimension: 'JP', text: '你更倾向于哪种购物方式：', options: { A: '列好清单，精准购买', B: '随意逛逛，看到喜欢的就买' }, mapping: { A: 'J', B: 'P' } },
  { id: 90, dimension: 'JP', text: '你更喜欢：', options: { A: '事情有了结、尘埃落定的感觉', B: '事情保持开放、有多种可能的感觉' }, mapping: { A: 'J', B: 'P' } },
  { id: 91, dimension: 'JP', text: '别人觉得你是一个：', options: { A: '守时、可靠的人', B: '随性、好相处的人' }, mapping: { A: 'J', B: 'P' } },
  { id: 92, dimension: 'JP', text: '面对多个任务时，你通常：', options: { A: '按优先级排好顺序逐一完成', B: '根据兴致在多任务之间切换' }, mapping: { A: 'J', B: 'P' } },
  { id: 93, dimension: 'JP', text: '你对"规则"的态度是：', options: { A: '规则让生活有序，应该遵守', B: '规则是参考，灵活变通更重要' }, mapping: { A: 'J', B: 'P' } }
];
